version: 2
jobs:
  # Build using our own builder base image using centos 7
  # This build is static, dependencies are bundled in the Falco binary
  "build/centos7":
    docker:
      - image: falcosecurity/falco-builder:latest
        environment:
          BUILD_TYPE: "release"
    steps:
      - checkout:
          path: /source/falco
      - run:
          name: Prepare project
          command: /usr/bin/entrypoint cmake
      - run:
          name: Build
          command: /usr/bin/entrypoint all
      - run:
          name: Run unit tests
          command: /usr/bin/entrypoint tests
      - run:
          name: Build packages
          command: /usr/bin/entrypoint package
      - persist_to_workspace:
          root: /
          paths:
            - build/release
            - source
      - run:
          name: Prepare artifacts
          command: |
            mkdir -p /tmp/packages
            cp /build/release/*.deb /tmp/packages
            cp /build/release/*.tar.gz /tmp/packages
            cp /build/release/*.rpm /tmp/packages
      - store_artifacts:
          path: /tmp/packages
          destination: /packages
  # Execute integration tests based on the build results coming from the "build/centos7" job
  "tests/integration":
    docker:
      - image: falcosecurity/falco-tester:latest
        environment:
          SOURCE_DIR: "/source"
          BUILD_DIR: "/build"
          BUILD_TYPE: "release"
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /
      - run:
          name: Execute integration tests
          command: /usr/bin/entrypoint test
      - store_test_results:
          path: /build/release/integration-tests-xunit
  "publish/packages-deb-dev-name":
    docker:
      - image: ubuntu:focal
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Setup
          command: |
            apt update -y
            apt-get install apt-utils bzip2 gpg python python3-pip -y
            pip install awscli
            echo $GPG_KEY | base64 -d | gpg --import
      - run:
          name: Publish deb-dev
          command: |
            echo hello
workflows:
  version: 2
  build_and_test:
    jobs:
      - "build/centos7"
      - "tests/integration":
          requires:
            - "build/centos7"
      - "publish/packages-deb-dev-name":
          context:
            - falco
            - test-infra
          filters:
            tags:
              ignore: /.*/
            branches:
              only: test/circleci
          requires:
            - "tests/integration"
